customhost = "reyesemployee.ccxxwexi7thf.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "reyesemployee"
custombucket = "reyes-employee"
customregion = "us-east-1"
